config/routes.rb
Rails.application.routes.draw do
  resources :alunos
  resources :turmas
  resources :professors
  resources :materia
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/aluno.rb
class Aluno < ApplicationRecord
  belongs_to :turma
  belongs_to :materia
  belongs_to :professor
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/materium.rb
class Materium < ApplicationRecord
end

app/models/professor.rb
class Professor < ApplicationRecord
end

app/models/turma.rb
class Turma < ApplicationRecord
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: [:show, :edit, :update, :destroy]

  # GET /alunos
  # GET /alunos.json
  def index
    @alunos = Aluno.all
  end

  # GET /alunos/1
  # GET /alunos/1.json
  def show
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  end

  # GET /alunos/1/edit
  def edit
  end

  # POST /alunos
  # POST /alunos.json
  def create
    @aluno = Aluno.new(aluno_params)

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to @aluno, notice: 'Aluno was successfully created.' }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1
  # PATCH/PUT /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to @aluno, notice: 'Aluno was successfully updated.' }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1
  # DELETE /alunos/1.json
  def destroy
    @aluno.destroy
    respond_to do |format|
      format.html { redirect_to alunos_url, notice: 'Aluno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aluno_params
      params.require(:aluno).permit(:nome, :idade, :turma_id, :materia_id, :professor_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/materia_controller.rb
class MateriaController < ApplicationController
  before_action :set_materium, only: [:show, :edit, :update, :destroy]

  # GET /materia
  # GET /materia.json
  def index
    @materia = Materium.all
  end

  # GET /materia/1
  # GET /materia/1.json
  def show
  end

  # GET /materia/new
  def new
    @materium = Materium.new
  end

  # GET /materia/1/edit
  def edit
  end

  # POST /materia
  # POST /materia.json
  def create
    @materium = Materium.new(materium_params)

    respond_to do |format|
      if @materium.save
        format.html { redirect_to @materium, notice: 'Materium was successfully created.' }
        format.json { render :show, status: :created, location: @materium }
      else
        format.html { render :new }
        format.json { render json: @materium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materia/1
  # PATCH/PUT /materia/1.json
  def update
    respond_to do |format|
      if @materium.update(materium_params)
        format.html { redirect_to @materium, notice: 'Materium was successfully updated.' }
        format.json { render :show, status: :ok, location: @materium }
      else
        format.html { render :edit }
        format.json { render json: @materium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materia/1
  # DELETE /materia/1.json
  def destroy
    @materium.destroy
    respond_to do |format|
      format.html { redirect_to materia_url, notice: 'Materium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_materium
      @materium = Materium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def materium_params
      params.require(:materium).permit(:materia)
    end
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: [:show, :edit, :update, :destroy]

  # GET /professors
  # GET /professors.json
  def index
    @professors = Professor.all
  end

  # GET /professors/1
  # GET /professors/1.json
  def show
  end

  # GET /professors/new
  def new
    @professor = Professor.new
  end

  # GET /professors/1/edit
  def edit
  end

  # POST /professors
  # POST /professors.json
  def create
    @professor = Professor.new(professor_params)

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: 'Professor was successfully created.' }
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professors/1
  # PATCH/PUT /professors/1.json
  def update
    respond_to do |format|
      if @professor.update(professor_params)
        format.html { redirect_to @professor, notice: 'Professor was successfully updated.' }
        format.json { render :show, status: :ok, location: @professor }
      else
        format.html { render :edit }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professors/1
  # DELETE /professors/1.json
  def destroy
    @professor.destroy
    respond_to do |format|
      format.html { redirect_to professors_url, notice: 'Professor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professor
      @professor = Professor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def professor_params
      params.require(:professor).permit(:nome, :materia, :horario, :turma)
    end
end

app/controllers/turmas_controller.rb
class TurmasController < ApplicationController
  before_action :set_turma, only: [:show, :edit, :update, :destroy]

  # GET /turmas
  # GET /turmas.json
  def index
    @turmas = Turma.all
  end

  # GET /turmas/1
  # GET /turmas/1.json
  def show
  end

  # GET /turmas/new
  def new
    @turma = Turma.new
  end

  # GET /turmas/1/edit
  def edit
  end

  # POST /turmas
  # POST /turmas.json
  def create
    @turma = Turma.new(turma_params)

    respond_to do |format|
      if @turma.save
        format.html { redirect_to @turma, notice: 'Turma was successfully created.' }
        format.json { render :show, status: :created, location: @turma }
      else
        format.html { render :new }
        format.json { render json: @turma.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turmas/1
  # PATCH/PUT /turmas/1.json
  def update
    respond_to do |format|
      if @turma.update(turma_params)
        format.html { redirect_to @turma, notice: 'Turma was successfully updated.' }
        format.json { render :show, status: :ok, location: @turma }
      else
        format.html { render :edit }
        format.json { render json: @turma.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turmas/1
  # DELETE /turmas/1.json
  def destroy
    @turma.destroy
    respond_to do |format|
      format.html { redirect_to turmas_url, notice: 'Turma was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turma
      @turma = Turma.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def turma_params
      params.require(:turma).permit(:turma, :turno, :materia, :aluno, :professor)
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/materia_helper.rb
module MateriaHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/turmas_helper.rb
module TurmasHelper
end

app/views/alunos/_form.html.erb
<%= form_with(model: aluno, local: true) do |form| %>
  <% if aluno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aluno.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
      <% aluno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :idade %>
    <%= form.date_select :idade %>
  </div>

  <div class="field">
    <%= form.label :turma_id %>
    <%= form.text_field :turma_id %>
  </div>

  <div class="field">
    <%= form.label :materia_id %>
    <%= form.text_field :materia_id %>
  </div>

  <div class="field">
    <%= form.label :professor_id %>
    <%= form.text_field :professor_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/alunos/edit.html.erb
<h1>Editing Aluno</h1>

<%= render 'form', aluno: @aluno %>

<%= link_to 'Show', @aluno %> |
<%= link_to 'Back', alunos_path %>

app/views/alunos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alunos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Idade</th>
      <th>Turma</th>
      <th>Materia</th>
      <th>Professor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alunos.each do |aluno| %>
      <tr>
        <td><%= aluno.nome %></td>
        <td><%= aluno.idade %></td>
        <td><%= aluno.turma %></td>
        <td><%= aluno.materia %></td>
        <td><%= aluno.professor %></td>
        <td><%= link_to 'Show', aluno %></td>
        <td><%= link_to 'Edit', edit_aluno_path(aluno) %></td>
        <td><%= link_to 'Destroy', aluno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aluno', new_aluno_path %>

app/views/alunos/new.html.erb
<h1>New Aluno</h1>

<%= render 'form', aluno: @aluno %>

<%= link_to 'Back', alunos_path %>

app/views/alunos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @aluno.nome %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @aluno.idade %>
</p>

<p>
  <strong>Turma:</strong>
  <%= @aluno.turma %>
</p>

<p>
  <strong>Materia:</strong>
  <%= @aluno.materia %>
</p>

<p>
  <strong>Professor:</strong>
  <%= @aluno.professor %>
</p>

<%= link_to 'Edit', edit_aluno_path(@aluno) %> |
<%= link_to 'Back', alunos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EscolaDevworks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/materia/_form.html.erb
<%= form_with(model: materium, local: true) do |form| %>
  <% if materium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(materium.errors.count, "error") %> prohibited this materium from being saved:</h2>

      <ul>
      <% materium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :materia %>
    <%= form.text_field :materia %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/materia/edit.html.erb
<h1>Editing Materium</h1>

<%= render 'form', materium: @materium %>

<%= link_to 'Show', @materium %> |
<%= link_to 'Back', materia_path %>

app/views/materia/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Materia</h1>

<table>
  <thead>
    <tr>
      <th>Materia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materia.each do |materium| %>
      <tr>
        <td><%= materium.materia %></td>
        <td><%= link_to 'Show', materium %></td>
        <td><%= link_to 'Edit', edit_materium_path(materium) %></td>
        <td><%= link_to 'Destroy', materium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Materium', new_materium_path %>

app/views/materia/new.html.erb
<h1>New Materium</h1>

<%= render 'form', materium: @materium %>

<%= link_to 'Back', materia_path %>

app/views/materia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Materia:</strong>
  <%= @materium.materia %>
</p>

<%= link_to 'Edit', edit_materium_path(@materium) %> |
<%= link_to 'Back', materia_path %>

app/views/professors/_form.html.erb
<%= form_with(model: professor, local: true) do |form| %>
  <% if professor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(professor.errors.count, "error") %> prohibited this professor from being saved:</h2>

      <ul>
      <% professor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :materia %>
    <%= form.text_field :materia %>
  </div>

  <div class="field">
    <%= form.label :horario %>
    <%= form.datetime_select :horario %>
  </div>

  <div class="field">
    <%= form.label :turma %>
    <%= form.text_field :turma %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/professors/edit.html.erb
<h1>Editing Professor</h1>

<%= render 'form', professor: @professor %>

<%= link_to 'Show', @professor %> |
<%= link_to 'Back', professors_path %>

app/views/professors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Professors</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Materia</th>
      <th>Horario</th>
      <th>Turma</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @professors.each do |professor| %>
      <tr>
        <td><%= professor.nome %></td>
        <td><%= professor.materia %></td>
        <td><%= professor.horario %></td>
        <td><%= professor.turma %></td>
        <td><%= link_to 'Show', professor %></td>
        <td><%= link_to 'Edit', edit_professor_path(professor) %></td>
        <td><%= link_to 'Destroy', professor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Professor', new_professor_path %>

app/views/professors/new.html.erb
<h1>New Professor</h1>

<%= render 'form', professor: @professor %>

<%= link_to 'Back', professors_path %>

app/views/professors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @professor.nome %>
</p>

<p>
  <strong>Materia:</strong>
  <%= @professor.materia %>
</p>

<p>
  <strong>Horario:</strong>
  <%= @professor.horario %>
</p>

<p>
  <strong>Turma:</strong>
  <%= @professor.turma %>
</p>

<%= link_to 'Edit', edit_professor_path(@professor) %> |
<%= link_to 'Back', professors_path %>

app/views/turmas/_form.html.erb
<%= form_with(model: turma, local: true) do |form| %>
  <% if turma.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(turma.errors.count, "error") %> prohibited this turma from being saved:</h2>

      <ul>
      <% turma.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :turma %>
    <%= form.text_field :turma %>
  </div>

  <div class="field">
    <%= form.label :turno %>
    <%= form.text_field :turno %>
  </div>

  <div class="field">
    <%= form.label :materia %>
    <%= form.text_field :materia %>
  </div>

  <div class="field">
    <%= form.label :aluno %>
    <%= form.text_field :aluno %>
  </div>

  <div class="field">
    <%= form.label :professor %>
    <%= form.text_field :professor %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/turmas/edit.html.erb
<h1>Editing Turma</h1>

<%= render 'form', turma: @turma %>

<%= link_to 'Show', @turma %> |
<%= link_to 'Back', turmas_path %>

app/views/turmas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Turmas</h1>

<table>
  <thead>
    <tr>
      <th>Turma</th>
      <th>Turno</th>
      <th>Materia</th>
      <th>Aluno</th>
      <th>Professor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @turmas.each do |turma| %>
      <tr>
        <td><%= turma.turma %></td>
        <td><%= turma.turno %></td>
        <td><%= turma.materia %></td>
        <td><%= turma.aluno %></td>
        <td><%= turma.professor %></td>
        <td><%= link_to 'Show', turma %></td>
        <td><%= link_to 'Edit', edit_turma_path(turma) %></td>
        <td><%= link_to 'Destroy', turma, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Turma', new_turma_path %>

app/views/turmas/new.html.erb
<h1>New Turma</h1>

<%= render 'form', turma: @turma %>

<%= link_to 'Back', turmas_path %>

app/views/turmas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Turma:</strong>
  <%= @turma.turma %>
</p>

<p>
  <strong>Turno:</strong>
  <%= @turma.turno %>
</p>

<p>
  <strong>Materia:</strong>
  <%= @turma.materia %>
</p>

<p>
  <strong>Aluno:</strong>
  <%= @turma.aluno %>
</p>

<p>
  <strong>Professor:</strong>
  <%= @turma.professor %>
</p>

<%= link_to 'Edit', edit_turma_path(@turma) %> |
<%= link_to 'Back', turmas_path %>